apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pv-claim
  namespace: client-postgres
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
